In [15]:
data="""customer_id,name,age,city,email,purchase_amount,rating
ID_1000,emily white,25,New York,emily.w@example.com,,4
1001,jane smith,35,Miami,charlie.g@example.com,10.5,4
1002,jane smith,45,houston,alice.j@example.com,250.0,3
1003,,45,houston,charlie.g@example.com,23.4,five
1004,emily white,35,BOSTON,alice.j@example.com,23.4,4
1005,emily white,twenty,seattle,john.doe@example.com,55.0,4
1006,DAVID BLACK,,los angeles,david.b@example.com,10.5,4.5
1007,emily white,55,los angeles,alice.j@example.com,55.0,4
1008,jane smith,60,houston,john.doe@example.com,10.5,2
1009, Alice Johnson ,60,BOSTON,john.doe@example.com,,5
1010,Charlie Green,30,Miami,john.doe@example.com,250.0,
1011,,25, CHICAGO , ,250.0,
1012,DAVID BLACK,30,los angeles,emily.w@example.com,missing,3
1013, Alice Johnson ,50,seattle, , ,None
1014,, ,seattle,emily.w@example.com,10.5,4
1015,emily white,34,None,bob.b@example.com,100.25,None
1016,emily white,twenty,seattle,john.doe@example.com,10.5,five
1017,,35,BOSTON,john.doe@example.com,missing,2
1018,bob brown,,los angeles,david.b@example.com,"150,50",1
1019,emily white,60,None,emily.w@example.com,,3
1020,bob brown,25,houston,emily.w@example.com,100.25,4.5
1021,emily white,45 ,New York,alice.j@example.com,99.99,3
1022,emily white,35,seattle,david.b@example.com,10.5,5
1023,bob brown,50,New York,jane.smith@example.com,23.4,2
1024,jane smith,55,los angeles,david.b@example.com,55.0,2
1025,DAVID BLACK,40,New York,alice.j@example.com,10.5,4
1026,DAVID BLACK,45,seattle,bob.b@example.com,,4
1027,,20,houston,charlie.g@example.com,250.0,1
1028,Charlie Green,34,houston,emily.w@example.com,55.0,1
1029,,60,Miami,alice.j@example.com,250.0,2
1030,john Doe,25,New York,john.doe@example.com,10.5,5
1031,,40,los angeles,jane.smith@example.com,250.0,4
1032,john Doe,25,,bob.b@example.com,250.0,4.5
1033,john Doe,,Miami,charlie.g@example.com,23.4,1
1034,john Doe,45,New York,bob.b@example.com,250.0,3
1035,Charlie Green,50,New York,charlie.g@example.com,23.4,2
1036,bob brown,20,Miami,charlie.g@example.com,100.25,2
1037,bob brown,30,BOSTON,john.doe@example.com,10.5,5
1038,Charlie Green,40,,jane.smith@example.com,,1
1039,,30,Miami,bob.b@example.com,"150,50",
1040,DAVID BLACK,50,New York,john.doe@example.com,23.4,2
1041,,30,New York,bob.b@example.com,10.5,3
1042,,55,,jane.smith@example.com,100.25,3
1043,bob brown,35,Miami,emily.w@example.com,,3
1044,Charlie Green,35,houston,bob.b@example.com,10.5,3
1045,jane smith,30,houston,david.b@example.com,23.4,4
1046,bob brown,50,New York,jane.smith@example.com,10.5,2
1047,Charlie Green,20,New York,,10.5,5
1048,jane smith,40,New York,charlie.g@example.com,,4
1049,,25,New York,bob.b@example.com,100.25,
1050,Charlie Green,55,Miami,jane.smith@example.com,10.5,5
1051,Charlie Green,50,houston,emily.w@example.com,,1
1052,john Doe,50,New York,jane.smith@example.com,250.0,1
1053,,35,CHICAGO ,,99.99,3
1054,jane smith,30,,bob.b@example.com,250.0,3
1055,bob brown,55,CHICAGO ,emily.w@example.com,,5
1056,john Doe,50,Miami,jane.smith@example.com,23.4,1
1057,,60,Miami,john.doe@example.com,23.4,5
1058,,25,seattle,emily.w@example.com,23.4,2
1059,bob brown,34,,emily.w@example.com,10.5,
1060,Charlie Green,25,houston,emily.w@example.com,23.4,5
1061,Charlie Green,45 ,BOSTON,charlie.g@example.com,55.0,2
1062,DAVID BLACK,35,Miami,david.b@example.com,99.99,1
1063,emily white,45,,jane.smith@example.com,,3
1064,,35,New York,charlie.g@example.com,,1
1065,john Doe,55,houston,bob.b@example.com,250.0,1
1066,,34,CHICAGO ,david.b@example.com,,4
1067,,34,seattle,jane.smith@example.com,250.0,4
1068,DAVID BLACK,35,,charlie.g@example.com,,4
1069,jane smith,55,New York,bob.b@example.com,23.4,4
1070,john Doe,35,CHICAGO ,emily.w@example.com,10.5,4
1071,,45 ,New York,emily.w@example.com,99.99,2
1072,john Doe,,Miami,jane.smith@example.com,100.25,5
1073, Alice Johnson ,34,New York,alice.j@example.com,10.5,3
1074,bob brown,20,Miami,jane.smith@example.com,,5
1075,john Doe,45,seattle,emily.w@example.com,55.0,1
1076,emily white,30,BOSTON,david.b@example.com,23.4,5
1077,emily white,25,seattle,bob.b@example.com,250.0,5
1078,,55,Miami,emily.w@example.com,55.0,3
1079,john Doe,34,houston,,100.25,1
1080,john Doe,45,,david.b@example.com,250.0,3
1081,jane smith,40,New York,charlie.g@example.com,,4
1082,jane smith,25,CHICAGO ,bob.b@example.com,23.4,5
1083, Alice Johnson ,,houston,bob.b@example.com,23.4,2
1084,,20,houston,david.b@example.com,23.4,4.5
1085,john Doe,twenty,seattle,david.b@example.com,10.5,3
1086,Charlie Green,30,New York,,10.5,3
1087,jane smith,60,Miami,alice.j@example.com,,4
1088,bob brown,60,CHICAGO ,,250.0,5
1089,Charlie Green,35,Miami,david.b@example.com,10.5,3
1090,emily white,45 ,New York,john.doe@example.com,,3
1091,bob brown,,New York,bob.b@example.com,23.4,4
1092,Charlie Green,45,BOSTON,alice.j@example.com,23.4,4
1093,emily white,55,Miami,jane.smith@example.com,10.5,2
1094,,60,New York,charlie.g@example.com,250.0,4
1095,emily white,35,seattle,emily.w@example.com,55.0,2
1096,emily white,34,Miami,bob.b@example.com,55.0,2
1097,Charlie Green,25,,bob.b@example.com,100.25,
1098,emily white,20,Miami,jane.smith@example.com,,4
1099,john Doe,50,,david.b@example.com,55.0,1
1100,john Doe,35,BOSTON,,250.0,1
1101,bob brown,35,BOSTON,,55.0,4
1102,jane smith,60,Miami,alice.j@example.com,23.4,4
1103,emily white,40,CHICAGO ,david.b@example.com,55.0,3
1104,john Doe,25,CHICAGO ,john.doe@example.com,55.0,5
1105,Charlie Green,30,Miami,john.doe@example.com,250.0,
1106,,25, CHICAGO , ,250.0,
1107,DAVID BLACK,30,los angeles,emily.w@example.com,missing,3
1108, Alice Johnson ,50,seattle, , ,None
1109,, ,seattle,emily.w@example.com,10.5,4
1110,emily white,34,None,bob.b@example.com,100.25,None
1111,emily white,twenty,seattle,john.doe@example.com,10.5,five
1112,,35,BOSTON,john.doe@example.com,missing,2
1113,bob brown,,los angeles,david.b@example.com,"150,50",1
1114,emily white,60,None,emily.w@example.com,,3
1115,bob brown,25,houston,emily.w@example.com,100.25,4.5
1116,emily white,45 ,New York,alice.j@example.com,99.99,3
1117,emily white,35,seattle,david.b@example.com,10.5,5
1118,bob brown,50,New York,jane.smith@example.com,23.4,2
1119,jane smith,55,los angeles,david.b@example.com,55.0,2

"""

In [16]:
with open("pandas_data.csv" , "w") as file:
    file.write(data)

In [ ]:
#reading csv data
import pandas as pd
df=pd.read_csv("pandas_data.csv")

In [18]:
df.isnull()

     customer_id   name    age   city  email  purchase_amount  rating
0          False  False  False  False  False             True   False
1          False  False  False  False  False            False   False
2          False  False  False  False  False            False   False
3          False   True  False  False  False            False   False
4          False  False  False  False  False            False   False
..           ...    ...    ...    ...    ...              ...     ...
115        False  False  False  False  False            False   False
116        False  False  False  False  False            False   False
117        False  False  False  False  False            False   False
118        False  False  False  False  False            False   False
119        False  False  False  False  False            False   False

[120 rows x 7 columns]

In [19]:
df.isnull().sum()

customer_id         0
name               24
age                 7
city               14
email               7
purchase_amount    19
rating             12
dtype: int64

In [20]:
df.dropna()

,customer_id,name,age,city,email,purchase_amount,rating
1,1001,jane smith,35,Miami,charlie.g@example.com,10.5,4
2,1002,jane smith,45,houston,alice.j@example.com,250.0,3
4,1004,emily white,35,BOSTON,alice.j@example.com,23.4,4
5,1005,emily white,twenty,seattle,john.doe@example.com,55.0,4
7,1007,emily white,55,los angeles,alice.j@example.com,55.0,4
8,1008,jane smith,60,houston,john.doe@example.com,10.5,2
12,1012,DAVID BLACK,30,los angeles,emily.w@example.com,missing,3
16,1016,emily white,twenty,seattle,john.doe@example.com,10.5,five
20,1020,bob brown,25,houston,emily.w@example.com,100.25,4.5
21,1021,emily white,45,New York,alice.j@example.com,99.99,3
22,1022,emily white,35,seattle,david.b@example.com,10.5,5
23,1023,bob brown,50,New York,jane.smith@example.com,23.4,2
24,1024,jane smith,55,los angeles,david.b@example.com,55.0,2
25,1025,DAVID BLACK,40,New York,alice.j@example.com,10.5,4
28,1028,Charlie Green,34,houston,emily.w@example.com,55.0,1
30,1030,john Doe,25,New York,john.doe@example.com,10.5,5
34,1034,john Doe,45,New York,bob.b@example.com,250.0,3
35,1035,Charlie Green,50,New York,charlie.g@example.com,23.4,2
36,1036,bob brown,20,Miami,charlie.g@example.com,100.25,2
37,1037,bob brown,30,BOSTON,john.doe@example.com,10.5,5
40,1040,DAVID BLACK,50,New York,john.doe@example.com,23.4,2
44,1044,Charlie Green,35,houston,bob.b@example.com,10.5,3
45,1045,jane smith,30,houston,david.b@example.com,23.4,4
46,1046,bob brown,50,New York,jane.smith@example.com,10.5,2
50,1050,Charlie Green,55,Miami,jane.smith@example.com,10.5,5
52,1052,john Doe,50,New York,jane.smith@example.com,250.0,1
56,1056,john Doe,50,Miami,jane.smith@example.com,23.4,1
60,1060,Charlie Green,25,houston,emily.w@example.com,23.4,5
61,1061,Charlie Green,45,BOSTON,charlie.g@example.com,55.0,2
62,1062,DAVID BLACK,35,Miami,david.b@example.com,99.99,1
65,1065,john Doe,55,houston,bob.b@example.com,250.0,1
69,1069,jane smith,55,New York,bob.b@example.com,23.4,4
70,1070,john Doe,35,CHICAGO,emily.w@example.com,10.5,4
73,1073,Alice Johnson,34,New York,alice.j@example.com,10.5,3
75,1075,john Doe,45,seattle,emily.w@example.com,55.0,1
76,1076,emily white,30,BOSTON,david.b@example.com,23.4,5
77,1077,emily white,25,seattle,bob.b@example.com,250.0,5
82,1082,jane smith,25,CHICAGO,bob.b@example.com,23.4,5
85,1085,john Doe,twenty,seattle,david.b@example.com,10.5,3
89,1089,Charlie Green,35,Miami,david.b@example.com,10.5,3
92,1092,Charlie Green,45,BOSTON,alice.j@example.com,23.4,4
93,1093,emily white,55,Miami,jane.smith@example.com,10.5,2
95,1095,emily white,35,seattle,emily.w@example.com,55.0,2
96,1096,emily white,34,Miami,bob.b@example.com,55.0,2
102,1102,jane smith,60,Miami,alice.j@example.com,23.4,4
103,1103,emily white,40,CHICAGO,david.b@example.com,55.0,3
104,1104,john Doe,25,CHICAGO,john.doe@example.com,55.0,5
107,1107,DAVID BLACK,30,los angeles,emily.w@example.com,missing,3
111,1111,emily white,twenty,seattle,john.doe@example.com,10.5,five
115,1115,bob brown,25,houston,emily.w@example.com,100.25,4.5
116,1116,emily white,45,New York,alice.j@example.com,99.99,3
117,1117,emily white,35,seattle,david.b@example.com,10.5,5
118,1118,bob brown,50,New York,jane.smith@example.com,23.4,2
119,1119,jane smith,55,los angeles,david.b@example.com,55.0,2

In [21]:
df["age"]=pd.to_numeric(df["age"],errors="coerce")
df["purchase_amount"]=pd.to_numeric(df["purchase_amount"],errors="coerce")
df["rating"]=pd.to_numeric(df["rating"],errors="coerce")
df["customer_id"]=pd.to_numeric(df["customer_id"],errors="coerce")


df["customer_id"]=df["customer_id"].fillna(0)
df["name"]=df["name"].fillna("name")
df["age"]=df["age"].fillna(df["age"].mean())
df["city"]=df["city"].fillna("city")
df["email"]=df["email"].fillna("missed@gmail.com")
df["purchase_amount"]=df["purchase_amount"].fillna(df["purchase_amount"].mean())
df["rating"]=df["rating"].fillna(0)

In [23]:
df

,customer_id,name,age,city,email,purchase_amount,rating
0,0.0,emily white,25.0,New York,emily.w@example.com,84.157065,4.0
1,1001.0,jane smith,35.0,Miami,charlie.g@example.com,10.500000,4.0
2,1002.0,jane smith,45.0,houston,alice.j@example.com,250.000000,3.0
3,1003.0,name,45.0,houston,charlie.g@example.com,23.400000,0.0
4,1004.0,emily white,35.0,BOSTON,alice.j@example.com,23.400000,4.0
...,...,...,...,...,...,...,...
115,1115.0,bob brown,25.0,houston,emily.w@example.com,100.250000,4.5
116,1116.0,emily white,45.0,New York,alice.j@example.com,99.990000,3.0
117,1117.0,emily white,35.0,seattle,david.b@example.com,10.500000,5.0
118,1118.0,bob brown,50.0,New York,jane.smith@example.com,23.400000,2.0
119,1119.0,jane smith,55.0,los angeles,david.b@example.com,55.000000,2.0

In [24]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
115    False
116    False
117    False
118    False
119    False
Length: 120, dtype: bool

In [26]:
df[df.duplicated()]

Empty DataFrame
Columns: [customer_id, name, age, city, email, purchase_amount, rating]
Index: []

In [27]:
df.drop_duplicates()

,customer_id,name,age,city,email,purchase_amount,rating
0,0.0,emily white,25.0,New York,emily.w@example.com,84.157065,4.0
1,1001.0,jane smith,35.0,Miami,charlie.g@example.com,10.500000,4.0
2,1002.0,jane smith,45.0,houston,alice.j@example.com,250.000000,3.0
3,1003.0,name,45.0,houston,charlie.g@example.com,23.400000,0.0
4,1004.0,emily white,35.0,BOSTON,alice.j@example.com,23.400000,4.0
...,...,...,...,...,...,...,...
115,1115.0,bob brown,25.0,houston,emily.w@example.com,100.250000,4.5
116,1116.0,emily white,45.0,New York,alice.j@example.com,99.990000,3.0
117,1117.0,emily white,35.0,seattle,david.b@example.com,10.500000,5.0
118,1118.0,bob brown,50.0,New York,jane.smith@example.com,23.400000,2.0
119,1119.0,jane smith,55.0,los angeles,david.b@example.com,55.000000,2.0

In [28]:
df.shape

(120, 7)

In [29]:
df.to_csv("cleaned_customer_data.csv" , index=False)